# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('title',)},
        ),
    ]
